version: '3.8'

services:
  #banco de dados MySQL
  db:
    image: mysql:8.0
    container_name: veritas-db
    restart: always
    environment:
      MYSQL_DATABASE: universidade_veritas
      MYSQL_ROOT_PASSWORD: sua_senha_aqui
    ports:
      - "3306:3306"
    volumes:
      - ./estrutura.sql:/docker-entrypoint-initdb.d/estrutura.sql 

  #aplicação Flask
  web:
    image: daikrnie/universidade-veritas:v1
    container_name: veritas-app
    restart: always
    ports:
      - "5000:5000" 
    env_file:
      - .env
    depends_on:
      - db 